# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/democircleci

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Build app
      - run: gradle clean build
      - persist_to_workspace:
          root: ~/democircleci
          paths:
            - Dockerfile
            - build



  build_docker:
    environment:
      DOCKER_FILE: "Dockerfile"
      SERVICE: "democircle"
    working_directory: ~/democircleci
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/democircleci
      - run:
          name: Build Docker image
          command:  docker build --file ${DOCKER_FILE} -t image .
      - run:
          name: get env from context
          command: echo $NEXUS_USER

workflows:
  version: 2
  build_circleci:
    jobs:
      - build:
          context:
            - project_secrets
          filters:
            branches:
              only: circleci-project-setup
      - build_docker:
          context:
            - project_secrets
          requires:
            - build
          filters:
            branches:
              only: circleci-project-setup
